default:
  SALES_REP_DATA: "data/salesreps.RDS"
  CUSTOMER_UNIQUE_ID_COL: "CONTRACT_SOLDTOID"
  CUTOMER_NAME_COL: "SOLDTO_GUO_NAME"
  CUTOMER_SIZE_COL: "ACCOUNT_INFO_VALUE"
  LONGITUDE_COL: "longitude"
  LATITUDE_COL: "latitude"
  
  SALES_REP_LONGITUDE_COL: "longitude"
  SALES_REP_LATITUDE_COL: "latitude"
  SALES_REP_NAME_COL: "salesmanager"
  SALES_REP_ICON_COL: "icons"
  
  SELECTED_CUSTOMERS_DISPLAY_COLUMS: ["CONTRACT_SOLDTOID", "SOLDTO_GUO_NAME", "Region", "EMP_SIZE","TURNOVER_SIZE","INFO_VALUE_SIZE","SOLDTO_POSTCODE"]
  
  INITIAL_SEGMENT_COLS: ["CCH_BUSINESS_TYPE","ACCOUNT_SFDC_ID","SOLDTO_GUO_NAME","SOLDTO_ADDRESS","SOLDTO_TOWN","SOLDTO_POSTCODE",
                         "INDUSTRY","SOLDTO_EMAIL","SOLDTO_PHONE", "CONTRACT_SHIPTOID","SHIPTO_FIRST_NAME","SHIPTO_LAST_NAME","SHIPTO_JOB_TITLE",
                         "SHIPTO_EMAIL","SHIPTO_PHONE","LATEST_RENEWAL","EARLIEST_RENEWAL","STATUS","CCH_INFO_VALUE","CRONER_INFO_VALUE"]
  
production:
  trials: 30
  dataset: "data.csv"
