default:
  FIRST_ITEM: 1
  CURRENCY: '£'
  CURRENCY_ICON: 'gbp'
  VALUE_DENOMINATION: 1000000
  VAUE_IN: 'Million'

  SALES_REP_DATA: "data/salesreps.RDS"
  
  # SALES REP COLS
  SALES_REP_LONGITUDE_COL: "longitude"
  SALES_REP_LATITUDE_COL: "latitude"
  SALES_REP_NAME_COL: "salesmanager"
  SALES_REP_ICON_COL: "icons"
  
  # CUSTOMER COLS
  CUSTOMER_UNIQUE_ID_COL: "CONTRACT_SOLDTOID"
  CUTOMER_NAME_COL: "SOLDTO_GUO_NAME"
  CUTOMER_SIZE_COL: "ACCOUNT_INFO_VALUE"
  LONGITUDE_COL: "longitude"
  LATITUDE_COL: "latitude"
  
  #CONTRACT COLS
  CONTRACT_UNIQUE_ID_COL: 'CONTRACT_SAP_ID'
  #CONTRACT_VALUE_COL: 'ACCOUNT_INFO_VALUE'
  CONTRACT_VALUE_COL: 'CONTRACT_VALUE'
  SUMMARY_CONTRACTS_PREVIEW_COLS: ['CONTRACT_SAP_ID','CONTRACT_DESCRIPTION','CONTRACT_STATUS','CONTRACT_VALUE','CONTRACT_STARTDATE','CONTRACT_ENDDATE']
  
  #PRODUCT COLS
  PRODUCT_UNIQUE_ID_COL: 'PRODUCT_CODE'
  SUMMARY_PRODUCT_PREVIEW_COLS: ['PRODUCT_CODE','PRODUCT_FAMILY']
  
  #CONTACT COLS
  CONTACT_UNIQUE_ID_COL: 'CONTRACT_SHIPTOID'
  SUMMARY_CONTACT_PREVIEW_COLS: ['SHIPTO_FIRST_NAME','SHIPTO_LAST_NAME','SHIPTO_EMAIL','SHIPTO_PHONE']
  CONTACT_PHONE_COL: 'SHIPTO_PHONE'
  CONTACT_EMAIL_COL: 'SHIPTO_EMAIL'
  
  # POPUP COLS
  POPUP_AGG_UNIQUE_COUNT_COLS: ['CONTRACT_SHIPTOID', 'CONTRACT_SAP_ID','PRODUCT_CODE']
  POPUP_AGG_SUM_COLS: ['CONTRACT_VALUE']
  POPUP_AGG_CONCAT_COLS: []
  POPUP_KEEP_FIRST_COLS: ['ACCOUNT_INFO_VALUE', 'SOLDTO_ADDRESS','SOLDTO_POSTCODE','SOLDTO_PHONE']
  POPUP_KEEP_LAST_COLS: []
  
  SUMMARY_AGG_UNIQUE_COLS: ['CONTRACT_SOLDTOID']
  SUMMARY_KEEP_FIRST_COLS: ['ACCOUNT_SFDC_ID','CCH_INFO_VALUE','CRONER_INFO_VALUE','EARLIEST_RENEWAL','LATEST_RENEWAL']
  
  
  # LANDING PAGE CHARTS
  DONUT_ONE_COL: 'EMP_SIZE'
  DONUT_TWO_COL: 'STATUS'
  BAR_CHART_COL: 'PRODUCT_CODE'
  
  
  # LANDING PAGE FILTER COLUMNS
  FILTER_CATEGORY_COLS: ['EMP_SIZE', 'TURNOVER_SIZE', 'INFO_VALUE_SIZE', 'Region', 'CCH_BUSINESS_TYPE', 'STATUS', 'CONTRACT_STATUS', 'BRAND']
  FILTER_FREETEXT_COLS: ['PRODUCT_CODE', 'JOB_TITLE']
  
  
  SELECTED_CUSTOMERS_DISPLAY_COLUMS: ["CONTRACT_SOLDTOID", "SOLDTO_GUO_NAME", "Region", "EMP_SIZE","TURNOVER_SIZE","INFO_VALUE_SIZE","SOLDTO_POSTCODE"]
  
  INITIAL_SEGMENT_COLS: ["CCH_BUSINESS_TYPE","ACCOUNT_SFDC_ID","SOLDTO_GUO_NAME","SOLDTO_ADDRESS","SOLDTO_TOWN","SOLDTO_POSTCODE",
                         "INDUSTRY","SOLDTO_EMAIL","SOLDTO_PHONE", "CONTRACT_SHIPTOID","SHIPTO_FIRST_NAME","SHIPTO_LAST_NAME","SHIPTO_JOB_TITLE",
                         "SHIPTO_EMAIL","SHIPTO_PHONE","LATEST_RENEWAL","EARLIEST_RENEWAL","STATUS","CCH_INFO_VALUE","CRONER_INFO_VALUE"]
  SEGMENT_Y_AXIS_COLS: ["NONE","BUSINESS_UNIT", "BRAND","CONTRACT_STATUS", "PRODUCT_FAMILY", "PRODUCT_CODE","EMP_SIZE", "INFO_VALUE_SIZE", "TURNOVER_SIZE"]
  
  
  # CHARTS PAGE
  BAR_CHART_COLS: ['INDUSTRY']
  
  
  # SEGMENTATION COLS
  SEGMENT_AGG_COLS: ['SOLDTO_GUO_NAME', 'ACCOUNT_SFDC_ID', 'CONTRACT_SOLDTOID', 'CONTRACT_SAP_ID', 'PRODUCT_CODE', 'PRODUCT_FAMILY', 'CONTRACT_VALUE', 
                      'NUMBEROFEMPLOYEES', 'ANNUALREVENUE']
  
  
production:
  trials: 30
  dataset: "data.csv"
