library(config)

config <- config::get()


FIRST_ITEM = config$FIRST_ITEM

SALES_REP_DATA = config$SALES_REP_DATA

#' COLUMN MAPPING TO BE MOVED TO CONFIG
CUSTOMER_UNIQUE_ID_COL = config$CUSTOMER_UNIQUE_ID_COL
CUSTOMER_NAME_COL = config$CUTOMER_NAME_COL
CUTOMER_SIZE_COL = config$CUTOMER_SIZE_COL
LONGITUDE_COL = config$LONGITUDE_COL
LATITUDE_COL = config$LATITUDE_COL


POPUP_AGG_UNIQUE_COUNT_COLS = config$POPUP_AGG_UNIQUE_COUNT_COLS
POPUP_AGG_SUM_COLS = config$POPUP_AGG_SUM_COLS
POPUP_AGG_CONCAT_COLS = config$POPUP_AGG_CONCAT_COLS
POPUP_KEEP_FIRST_COLS = config$POPUP_KEEP_FIRST_COLS


SALES_REP_LONGITUDE_COL = config$SALES_REP_LONGITUDE_COL
SALES_REP_LATITUDE_COL = config$SALES_REP_LATITUDE_COL
SALES_REP_NAME_COL = config$SALES_REP_NAME_COL
SALES_REP_ICON_COL = config$SALES_REP_ICON_COL


SELECTED_CUSTOMERS_DISPLAY_COLUMS = config$SELECTED_CUSTOMERS_DISPLAY_COLUMS

INITIAL_SEGMENT_COLS = config$INITIAL_SEGMENT_COLS
