library(config)

config <- config::get()


FIRST_ITEM = config$FIRST_ITEM
CURRENCY = config$CURRENCY
CURRENCY_ICON = config$CURRENCY_ICON
VALUE_DENOMINATION = config$VALUE_DENOMINATION
VALUE_IN = config$VALUE_IN

SALES_REP_DATA = config$SALES_REP_DATA

# CUSTOMER COLS
CUSTOMER_UNIQUE_ID_COL = config$CUSTOMER_UNIQUE_ID_COL
CUSTOMER_NAME_COL = config$CUTOMER_NAME_COL
CUTOMER_SIZE_COL = config$CUTOMER_SIZE_COL
LONGITUDE_COL = config$LONGITUDE_COL
LATITUDE_COL = config$LATITUDE_COL

#CONTRACT COLS
CONTRACT_UNIQUE_ID_COL = config$CONTRACT_UNIQUE_ID_COL
SUMMARY_CONTRACTS_PREVIEW_COLS  = config$SUMMARY_CONTRACTS_PREVIEW_COLS
CONTRACT_VALUE_COL = config$CONTRACT_VALUE_COL

#PRODUCT COLS
PRODUCT_UNIQUE_ID_COL = config$PRODUCT_UNIQUE_ID_COL
SUMMARY_PRODUCT_PREVIEW_COLS  = config$SUMMARY_PRODUCT_PREVIEW_COLS

#CONTACT COLS
CONTACT_UNIQUE_ID_COL = config$CONTACT_UNIQUE_ID_COL
SUMMARY_CONTACT_PREVIEW_COLS  = config$SUMMARY_CONTACT_PREVIEW_COLS
CONTACT_PHONE_COL = config$CONTACT_PHONE_COL
CONTACT_EMAIL_COL = config$CONTACT_EMAIL_COL

# CUSTOMER POPUP COLS
POPUP_AGG_UNIQUE_COUNT_COLS = config$POPUP_AGG_UNIQUE_COUNT_COLS
POPUP_AGG_SUM_COLS = config$POPUP_AGG_SUM_COLS
POPUP_AGG_CONCAT_COLS = config$POPUP_AGG_CONCAT_COLS
POPUP_KEEP_FIRST_COLS = config$POPUP_KEEP_FIRST_COLS


SUMMARY_AGG_UNIQUE_COLS = config$SUMMARY_AGG_UNIQUE_COLS
SUMMARY_KEEP_FIRST_COLS = config$SUMMARY_KEEP_FIRST_COLS

# LANDING PAGE CHARTS
DONUT_ONE_COL = config$DONUT_ONE_COL
DONUT_TWO_COL = config$DONUT_TWO_COL
BAR_CHART_COL = config$BAR_CHART_COL

# LANDING PAGE FILTERS
FILTER_CATEGORY_COLS = config$FILTER_CATEGORY_COLS
FILTER_FREETEXT_COLS = config$FILTER_FREETEXT_COLS

# CHARTS PAGE
BAR_CHART_COLS = config$BAR_CHART_COLS

# SEGMENTATION COLS
SEGMENT_AGG_COLS = config$SEGMENT_AGG_COLS


SALES_REP_LONGITUDE_COL = config$SALES_REP_LONGITUDE_COL
SALES_REP_LATITUDE_COL = config$SALES_REP_LATITUDE_COL
SALES_REP_NAME_COL = config$SALES_REP_NAME_COL
SALES_REP_ICON_COL = config$SALES_REP_ICON_COL


SELECTED_CUSTOMERS_DISPLAY_COLUMS = config$SELECTED_CUSTOMERS_DISPLAY_COLUMS

INITIAL_SEGMENT_COLS = config$INITIAL_SEGMENT_COLS
SEGMENT_Y_AXIS_COLS = config$SEGMENT_Y_AXIS_COLS

OPENAI_MAX_TOKENS = config$OPENAI_MAX_TOKENS
